version: 0.2

phases:
  install:
    commands:
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.1/2023-04-19/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
  pre_build:
    commands:
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo Deploying to Amazon EKS Cluster...
      - kubectl apply -f aws-eks.yaml