apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        service_name: service_a
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80