version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing source NPM dependencies...
      - npm install    
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp --recursive ./dist s3://udemy-devops-codebuild-linh/nodejs_artifacts/
artifacts:
  files:
    - dist/**
  discard-paths: yes