apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-test-cluster
  region: ap-southeast-1

nodeGroups:
  - name: my-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4